/**
 * Purpose: Production-ready reusable PDF Report Exporter utility using jsPDF and jspdf-autotable
 * Responsibilities: Render branded company header, report metadata box, styled data table with alternating rows,
 *                    repeating headers, landscape layout support, page numbers ("Page X of Y"), and footer text.
 * Dependencies: jspdf, jspdf-autotable
 * Export: exportPDF(), PDFColumn, ExportPDFOptions
 */
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface PDFColumn<T> {
  header: string;
  accessor: (item: T) => string | number | boolean | null | undefined;
}

export interface CompanyDetails {
  name?: string;
  address?: string;
  contact?: string;
  gstin?: string;
}

export interface ExportPDFOptions<T> {
  filename: string;
  reportTitle: string;
  data: T[];
  columns: PDFColumn<T>[];
  companyInfo?: CompanyDetails;
  appliedFilters?: Record<string, string | number | undefined | null>;
  generatedBy?: string;
  orientation?: 'portrait' | 'landscape';
}

const DEFAULT_COMPANY: CompanyDetails = {
  name: 'ShineCraft Billing Systems',
  address: '123 Business Avenue, Suite 400, Tech Park, Chennai - 600001, TN, India',
  contact: 'Phone: +91 98765 43210 | Email: billing@shinecraft.com',
  gstin: 'GSTIN: 33AAAAA0000A1Z5',
};

export function exportPDF<T>({
  filename,
  reportTitle,
  data,
  columns,
  companyInfo = DEFAULT_COMPANY,
  appliedFilters,
  generatedBy = 'System Admin',
  orientation = 'landscape',
}: ExportPDFOptions<T>): void {
  if (!data || data.length === 0) {
    throw new Error('No data available to export');
  }

  // 1. Initialize jsPDF document
  const doc = new jsPDF({
    orientation,
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  const margin = 14;

  // 2. Render Header (Company Branded Top Header)
  doc.setFillColor(15, 23, 42); // Dark slate (#0f172a)
  doc.rect(0, 0, pageWidth, 24, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text(companyInfo.name || DEFAULT_COMPANY.name!, margin, 11);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(203, 213, 225); // Light slate (#cbd5e1)
  const contactStr = `${companyInfo.address || DEFAULT_COMPANY.address!} | ${companyInfo.contact || DEFAULT_COMPANY.contact!}`;
  doc.text(contactStr, margin, 18);

  // 3. Render Report Title & Summary Box
  let startY = 32;

  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text(reportTitle, margin, startY);

  startY += 5;

  // Metadata Card / Filter summary bar
  doc.setFillColor(248, 250, 252); // Light background (#f8fafc)
  doc.setDrawColor(226, 232, 240); // Border color (#e2e8f0)
  doc.roundedRect(margin, startY, pageWidth - margin * 2, 16, 2, 2, 'FD');

  const todayStr = new Date().toISOString().slice(0, 10);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(51, 65, 85);

  const activeFilters = appliedFilters
    ? Object.entries(appliedFilters)
        .filter(([, v]) => v != null && v !== '' && v !== 'All')
        .map(([k, v]) => `${k}: ${v}`)
        .join(' | ')
    : '';

  const filterText = activeFilters ? activeFilters : 'None (All Records)';

  doc.text(`Export Date: ${todayStr}`, margin + 4, startY + 6);
  doc.text(`Total Records: ${data.length}`, margin + 70, startY + 6);
  doc.text(`Generated By: ${generatedBy}`, margin + 140, startY + 6);
  doc.text(`Applied Filters: ${filterText}`, margin + 4, startY + 12);

  startY += 22;

  // 4. Prepare Table Data
  const headers = columns.map((col) => col.header);
  const rows = data.map((item) =>
    columns.map((col) => {
      try {
        const val = col.accessor(item);
        if (val == null) return '';
        if (typeof val === 'boolean') return val ? 'Yes' : 'No';
        return String(val);
      } catch {
        return '';
      }
    })
  );

  // 5. Generate Table using jspdf-autotable
  autoTable(doc, {
    head: [headers],
    body: rows,
    startY: startY,
    margin: { top: 28, left: margin, right: margin, bottom: 20 },
    theme: 'grid',
    headStyles: {
      fillColor: [30, 41, 59], // Slate 800 (#1e293b)
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8,
      halign: 'left',
      cellPadding: 3,
    },
    bodyStyles: {
      fontSize: 7.5,
      textColor: [51, 65, 85], // Slate 700
      cellPadding: 2.5,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252], // Slate 50 (#f8fafc)
    },
    tableLineColor: [226, 232, 240],
    tableLineWidth: 0.1,
    styles: {
      overflow: 'linebreak',
      font: 'helvetica',
    },
    didDrawPage: (dataArg) => {
      // Header band on sub-pages
      if (dataArg.pageNumber > 1) {
        doc.setFillColor(15, 23, 42);
        doc.rect(0, 0, pageWidth, 16, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(10);
        doc.text(`${reportTitle} (Continued)`, margin, 10);
      }

      // Page Footer
      const pageCount = (doc as any).internal.getNumberOfPages();
      const currentPage = dataArg.pageNumber;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(100, 116, 139);

      // Left footer
      doc.text('Generated by Project Management System', margin, pageHeight - 8);

      // Right footer
      const pageStr = `Page ${currentPage} of ${pageCount}`;
      doc.text(pageStr, pageWidth - margin - doc.getTextWidth(pageStr), pageHeight - 8);
    },
  });

  // 6. Save PDF
  const finalFilename = filename.toLowerCase().endsWith('.pdf') ? filename : `${filename}.pdf`;
  doc.save(finalFilename);
}
